// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWrN0nvrfjJ4FcAJ83pWHWWOxRhEqZ8AA',
    appId: '1:9774358121:web:2b3f6a58961ac395154cf8',
    messagingSenderId: '9774358121',
    projectId: 'geminidietmaster',
    authDomain: 'geminidietmaster.firebaseapp.com',
    storageBucket: 'geminidietmaster.appspot.com',
    measurementId: 'G-XRQ802L707',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJdQLoSzziOT9r_Wl10rRIiHzOGlqd_4',
    appId: '1:9774358121:android:af223d0a1780ede2154cf8',
    messagingSenderId: '9774358121',
    projectId: 'geminidietmaster',
    storageBucket: 'geminidietmaster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSV-73EvuArPeWwChNBtO6Fmt6Y5GoOV4',
    appId: '1:9774358121:ios:ec5bda25b50a3fd0154cf8',
    messagingSenderId: '9774358121',
    projectId: 'geminidietmaster',
    storageBucket: 'geminidietmaster.appspot.com',
    iosBundleId: 'com.arrijal.dietMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSV-73EvuArPeWwChNBtO6Fmt6Y5GoOV4',
    appId: '1:9774358121:ios:ec5bda25b50a3fd0154cf8',
    messagingSenderId: '9774358121',
    projectId: 'geminidietmaster',
    storageBucket: 'geminidietmaster.appspot.com',
    iosBundleId: 'com.arrijal.dietMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWrN0nvrfjJ4FcAJ83pWHWWOxRhEqZ8AA',
    appId: '1:9774358121:web:a9c2151b33dc9801154cf8',
    messagingSenderId: '9774358121',
    projectId: 'geminidietmaster',
    authDomain: 'geminidietmaster.firebaseapp.com',
    storageBucket: 'geminidietmaster.appspot.com',
    measurementId: 'G-ZK1DPQFGG2',
  );
}
